services:
  - type: web
    name: dit-2026
    runtime: python
    rootDir: assessment
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:create_app() --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.12"
